ministryofjustice/hmpps-manage-offences-api

src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/model/external/sdrs/Offence.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/SDRSService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/TransformFunctions.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/integration/wiremock/SDRSApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/SDRSServiceIntTest.kt
src/test/resources/test_data/clear-all-data.sql

TODO (as separate work)
- Store everything returned from SDRS somewhere! (maybe the full json shape?)
- Add other attributes to our DB (e.g start and end dates)

OFFENCES-42 Save the data received from SDRS into the database - just some initial attributes

---

README.md
run-local.sh

plus will fix CVE-2022-0778 (needs a new image generating)

OFFENCES-44 Update README with instructions on how to run locally + update run-local.sh

---

Dockerfile

See https://github.com/ministryofjustice/hmpps-template-kotlin/pull/98

OFFENCES-56 Bring in line with kotlin template - run server class containers which forces the use of serverclass GC

---

src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/config/WebClientConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/repository/SdrsLoadResultHistoryRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/repository/SdrsLoadResultRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/resource/OffenceController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/OffenceService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/SDRSService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/resource/OffencesControllerIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/SDRSServiceIntTest.kt

The SDRS sync job runs every 20 minutes

OFFENCES-61 Add scheduled-job to synchronise with SDRS (used for full load and update)

---

src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/entity/Offence.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/model/PrisonApiOffence.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/resource/OffenceController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/OffenceService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/PrisonApiClient.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/integration/health/HealthCheckTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/integration/wiremock/PrisonApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/resource/OffencesControllerIntTest.kt
src/test/resources/application-test.yml
src/test/resources/test_data/insert-offence-data-that-exists-in-nomis.sql

This full sync with NOMIS still has a few outstanding issues - hence a few TODO's and is WIP

OFFENCES-72 Add endpoint that will fully sync up all offences with NOMIS

---

src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/entity/Schedule.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/model/Schedule.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/model/SchedulePart.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/model/SchedulePartIdAndOffenceId.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/repository/OffenceSchedulePartRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/repository/SchedulePartRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/repository/ScheduleRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/resource/ScheduleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/ScheduleService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/TransformFunctions.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/resource/ScheduleControllerIntTest.kt
src/test/resources/test_data/reset-all-data.sql

This is emerging functionality (adding maintenance of schedules and linking to offences) and is therefore WIP

OFFENCES-92 Add initial functionality for Schedules and linking them to offences

---

README.md
helm_deploy/values-preprod.yaml

OFFENCES-110 Change application insights configuration file for preprod

---

src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/entity/Offence.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/model/Offence.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/repository/OffenceRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/resource/OffenceController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/OffenceService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/TransformFunctions.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/resource/OffencesControllerIntTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/OffenceServiceTest.kt

New search functionality for demo (prototype work)
Enhanced unit tests will follow

MOP-45 New search endpoint for prototype demo - searches on code, description and legislation

---

src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/entity/HoCodesLoadHistory.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/enum/AnalyticalPlatformTableName.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/repository/HoCodesLoadHistoryRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/repository/HomeOfficeCodeRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/AwsS3Service.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/HoCodeService.kt
src/main/resources/migration/common/V28__ho_codes_load_history.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/HoCodeServiceTest.kt

TODO's
- Unit Tests, WIP so tests are sparse at the moment
- Figure out best way to do aws interaction tests (especially the async tests)
- Injest the other 3 tables
- Determine how we store the actual mapping data

MOP-60 Use production folder in AP for ho-code data - also add logic to only load from latest timestamped directory

---

helm_deploy/values-dev.yaml

This is to help testing with DELIUS integration in the dev environment

MOP-99 Point dev to production SDRS temporarily (SDRS staging is not working at the moment)

---

src/main/resources/migration/common/V37__add_nomis_legacy_schedule_data.sql

https://github.com/ministryofjustice/hmpps-manage-offences-api/assets/3595969/edd2a51b-194d-4121-8948-eca1cc0b6ccf

MOP-107 Move nomis legacy schedules into their own section alongside PCSC

---

src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/model/PcscLists.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/model/PcscMarkers.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/resource/ScheduleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/ScheduleService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/TransformFunctions.kt

MOP-125 Add endpoint to fetch all PCSC offences organised per list

---

src/main/resources/migration/common/V46__max_period_life_for_SX03235_and_SX03237.sql

* Sets the max period to life for SX03235 and SX03237 (and inchoate offences SX03235A and SX03237A)

Max penalty should be life for SX03235 and SX03237

---

src/main/resources/migration/common/V47__MOP_150_update_max_period_life_and_dates.sql

* Sets max period to life and the start date as required.
* Offence linking is best done through the UI for audit purpose.

Updates the offences to the new values

---

src/main/resources/migration/common/V47__MOP_150_update_max_period_life_and_dates.sql

This needs to be split into two parts

Revert "Updates the offences to the new values"

---

src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/entity/OffenceScheduleMapping.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/repository/OffenceScheduleMappingRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/resource/ScheduleController.kt

attempt to optimise query for retrieving pcsc indicators and sds-early-release-exclusions

MOP-177 query optimisation

---

Dockerfile

Correct Env syntax use JDK not JRE for build step

Build fixes

---

README.md
build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/config/CacheConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/repository/ScheduleRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/resource/ScheduleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/ScheduleService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/resource/ScheduleControllerIntTest.kt
src/test/resources/test_data/insert-torera-schedule-offences.sql

MOP-188 torera related codes
Introduce endpoint for TORERA related offence codes.
Cache results to mitigate any potential performance issues.

Mop 188 torera related codes

---

build.gradle.kts

MOP-200 upgrade swagger to fix incompatibility issue with previous upgrades

---

build.gradle.kts
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/config/CacheConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/config/ResourceServerConfiguration.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/model/ToreraSchedulePartCodes.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/repository/ScheduleRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/resource/ScheduleController.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/service/ScheduleService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/integration/IntegrationTestBase.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/manageoffencesapi/resource/ScheduleControllerIntTest.kt

Add additional endpoint to schedule controller, breaking down offence codes by schedule part.
Update Spring along with deprecated code.

Crs 2110 disable ersed eds
